# Generated by Django 3.0.13 on 2021-03-20 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField( upload_to='./static/images'),
            preserve_default=False,
        ),
    ]
