# Generated by Django 3.0.13 on 2021-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_auto_20210320_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
