# Generated by Django 3.0.13 on 2021-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_auto_20210320_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(to='jobapp.Employee'),
        ),
    ]
