# Generated by Django 3.0.13 on 2021-03-22 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_job_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employees',
        ),
        migrations.AddField(
            model_name='job',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.Employee'),
            preserve_default=False,
        ),
    ]
