# Generated by Django 3.0.13 on 2021-03-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_auto_20210322_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.Employee'),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.Employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job')),
            ],
        ),
    ]
