# Generated by Django 3.0.13 on 2021-03-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
